---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localpv-demo-pvc
spec:
  storageClassName: localpv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: localpv-demo-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh","-c","echo hello > /data/hello && sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: localpv-demo-pvc

